### ISSUE TITLE
Consider adding an additional Filter: "Milk Alternatives"

### ISSUE THREAD

**Issue by matthiasrossini** [pqvst/cafeandcowork#25]
TBD. if this includes food or not, but possible solutions might include:

**Drinks Only**
- Radio Box [ ] (yes/no) 
- Select Box (Oatmilk/Soymilk/All/Other)
- Text Input: "_author describes options_"

**Including Food**
- Select Box: Vegetarian Friendly, Vegan Friendly

**Comment by pqvst** [comment]
I'm wondering if maybe this would be the simplest?
```
lactose free milk: true/false
```

**Comment by pqvst** [comment]
Fixed
